spring.application.name=MACROBUS
spring.datasource.url=jdbc:mysql://localhost:3306/MacroBus_Production?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=Ngone1993
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
